functions.go
interpreter_test.go
scopes_test.go

This PR fixes a few minor linter warnings.
cc @springcomp

fix: minor linter warnings

---

.github/workflows/ci.yml

This PR runs ci
Strangely enough ci does not run 🤔

chore: run ci

---

functions.go
interpreter.go
pkg/util/util.go
pkg/util/util_test.go

This PR adds an `util` sub package

refactor: create util sub package

---

.github/workflows/codecov.yaml
.gitignore

fix: code coverage

---

api.go
pkg/interpreter/functions.go
pkg/interpreter/interpreter.go
pkg/interpreter/interpreter_test.go
pkg/interpreter/scopes.go
pkg/interpreter/scopes_test.go

This PR adds an `interpreter` sub package.

refactor: create interpreter sub package

---

.github/workflows/ci.yaml
.github/workflows/codecov.yaml

This PR fixes compliance tests.

fix: compliance tests

---

cmd/jpgo/main.go
compliance_test.go
pkg/api/api.go
pkg/api/api_test.go

This PR adds an `api` sub package.

refactor: create api sub package

---

pkg/api/api.go

This PR introduces the `JMESPath` interface instead of exposing a struct directly.

refactor: introduce JMESPath interface

---

pkg/interpreter/functions.go
pkg/interpreter/interpreter.go

This PR introduces the `Interpreter` interface.

refactor: introduce Interpreter interface

---

.golangci.yml
pkg/interpreter/functions.go
pkg/interpreter/interpreter.go
pkg/parsing/lexer.go
pkg/parsing/lexer_test.go
pkg/parsing/parser_test.go
pkg/util/util.go

chore: more linters - part 2

---

.golangci.yml
pkg/api/api.go
pkg/interpreter/functions.go
pkg/interpreter/interpreter.go

chore: more linters - part 3

---

pkg/interpreter/functions.go

This PR exposes functions related types.

refactor: expose functions related types

---

pkg/interpreter/functions.go

This PR simplifies the way we pass the interpreter to functions.

refactor: simplify passing interpreter to functions

---

pkg/api/api_test.go
pkg/interpreter/functions.go

This PR fixes non deterministic sorting.
Based on #37 changes
Fixes #38

fix: non deterministic sorting

---

pkg/api/api.go
pkg/api/api_test.go

This PR adds custom functions support.

feat: add custom functions support

---

.github/workflows/ci.yaml

This PR run tests with go 1.20.

chore: test with go 1.20

---

.github/workflows/codecov.yaml
Makefile

This PR takes compliance tests into account in code coverage.

chore: account for compliance tests in code coverage

---

README.md

This PR adds codecov badge in the README.

chore: add codecov badge to README

---

README.md

This PR adds go report card badge to README.

chore: add go report card badge to README

---

README.md

This PR adds license badge to readme.

chore: add license badge to readme

---

jp.go
pkg/api/api_test.go
pkg/functions/functions.go
pkg/interpreter/functions.go
pkg/interpreter/interpreter.go

This PR refactors expression ref handling.

refactor: expression ref handling

---

jp.go

This PR adds aliases for the `parsing` package

chore: add aliases for parsing package

---

.golangci.yml

chore: fix linter errors

---

cmd/jpgo/main.go
go.mod
go.sum

feat: use cobra for the CLI

---

pkg/api/api_test.go
pkg/functions/functions.go

Use deep equal in contains.
cc @springcomp

fix: use deep equal in contains

---

.github/workflows/codecov.yaml

Decouple unit tests and upload to codecov.

chore: decouple unit tests and upload to codecov

---

pkg/functions/default.go

Add descriptions for remaining functions.

feat: add descriptions for remaining functions
